title: "Kunmo Kim"
description: "High-speed SerDes • ADC-based receivers • Equalization"
theme: just-the-docs
color_scheme: nil          # or "dark", "light", or a custom scheme
search_enabled: false
aux_links:
  "Google Scholar":
    - "https://scholar.google.com/citations?user=Gjlk44MAAAAJ&hl=en"
  "GitHub":
    - "https://github.com/kunmok"
# Navigation order
nav_external_links_new_tab: true
permalink: pretty
just_the_docs:
  navigation_depth: 2
  show_navbar: true
  collections:
    pages:
      name: Pages
      nav_exclude: false
      permalink: "/:path/"
